rabbitmq:
  enable: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto # 自动确认模式（可选手动）
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
    virtual-host: /
canal:
  queue-name: canal.queue
